# ===================================================================
# JHipster Spring Cloud Config.
# ===================================================================

configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server, using gitlab !

jhipster:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
eureka:
    client:
        service-url:
            defaultZone: http://admin:admin@10.166.198.210:8761/eureka/
enviaportafirmas:
    datasource:
        url: jdbc:oracle:thin:@10.166.198.4:1521:SCAI
        username: GESFIR
        password: simeta

certificado:
    alias: (lp_qsep_m_es_p12_344_1825_sw_kpsc)_q8050008e_52758360v
    path: /var/opt/sife/certificados/SELLO_PREPRODUCCION_SGTI_2017.pfx
    secret: Cr1st0b4l7

sistemafirma:
    gesfir:
        repositorio:
            raiz: /opt/sife/SistemaFirma
            evidencias: ${sistemafirma.gesfir.repositorio.raiz}/evidencias
            documentos: ${sistemafirma.gesfir.repositorio.raiz}/documentos
            anexos: ${sistemafirma.gesfir.repositorio.raiz}/anexos
            firmas: ${sistemafirma.gesfir.repositorio.raiz}/firmas
            repository: ${sistemafirma.gesfir.repositorio.raiz}/archivosSubidos

    enviaportafirmas:
        gesfir:
            gestionDocSi: /pasarela-firma.xhtml
            gestionDocNo: /pasarela-firma-no-visualiza.xhtml
            url: http://127.0.0.1:8080/gesfir
        figesperws:
            endpoint: http://www-pre.sms.carm.es/figesperwsacceso/FigesperAccesoWS?wsdl
            user: jcg25l
            password: jcgwspr325
            timeOut: 30
        csv:
            key: /opt/sife/certificados/key.txt

ip:
    zipkin: 10.166.198.210
    logstash: 10.166.198.210
